name: youtube_player_iframe_example
description: Demonstrates how to use the youtube_player_iframe plugin.
publish_to: none
version: 5.0.0

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher_tizen: ^2.1.2

  youtube_player_iframe:
    path: ../
  webview_flutter_tizen: ^0.9.2
  go_router: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

icons_launcher:
  image_path: ../screenshots/logo.png
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
